title:              SONG2DU
email:              song6341@gachon.ac.kr
description:        Hi, I'm yidu song
author:             yidu song
baseurl:            ""
url:                "https://song2du.github.io"

# Social Profiles
twitter_username:   
github_username:    song2du
facebook_username:  
instagram_username:  song2du
linkedin_username:  yidu-song-552374346

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
